import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div id="__next">
          <div className="grid grid-cols-12 px-20 h-screen">
            <aside className="bg-amber-300 col-span-2">
              <nav className="p-4">
                <ul className="space-y-2">
                  <li><Link href="/" className="text-gray-800">Dashboard</Link></li>
                  <li><Link href="/invoices" className="text-gray-800">Invoices</Link></li>
                  <li><Link href="/clients" className="text-gray-800">Clients</Link></li>
                  <li><Link href="/settings" className="text-gray-800">Settings</Link></li>
                </ul>
              </nav>
            </aside>
            <main className="bg-cyan-100 col-span-10">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
